Adding tic tac toe example
meteor/examples pull request #5
Opened 2021-03-11 19:31 UTC by renanccastro

2021-03-19 20:08 UTC, filipenevola requested changes
Hi, thank you! :)

I've requested some changes and also you need to add your example to the main README

2021-03-19 20:08 UTC, filipenevola commented on tic-tac-toe/README.md
> +#Tic tac toe
It's missing how to set up and run the example.

2021-03-19 20:08 UTC, filipenevola commented on tic-tac-toe/package.json
> +    "@babel/runtime": "^7.11.2",
could you update the dependencies?

2021-03-19 20:08 UTC, filipenevola commented on tic-tac-toe/tests/main.js
> +describe("tic-tac-toe", function () {
could you remove it?

2021-08-24 03:50 UTC, filipenevola requested changes
I believe the application is not deployed at https://tic-tac-toe.meteorapp.com

Is it?

2021-08-24 14:22 UTC, renanccastro commented
Holy moly, yes, it wasn't.
Now it is!

2021-08-24 23:27 UTC, filipenevola approved these changes
We could improve the UI before promoting it. What do you think?

2021-08-24 23:28 UTC, merged